"""NDVI density sampler — gates tree scatter against Sentinel-2 canopy mask.

Reads ``assets/terrain/escobar_ndvi.png`` (8-bit grayscale, generated by
``scripts/make_ndvi_mask.py``) and exposes ``density_at(nx, ny) -> float``
in [0,1]. The (nx, ny) convention is the same as
``lqv.subscene.terrain_62ha_photoreal._sample_terrain_z``: normalized parcel
coords in [-0.5, +0.5], origin centred, +y = north. Bilinear sampling
matches the heightmap sampler so the NDVI gate aligns 1:1 with the displaced
terrain surface and the Sentinel-2 albedo.

Use this to discriminate canopy (high NDVI → high density → tree allowed)
from laterite paths / built / water (low NDVI → 0 density → tree rejected).
"""
from __future__ import annotations

import os

import bpy

_PROJECT_ROOT = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)
NDVI_PNG = os.path.join(_PROJECT_ROOT, "assets", "terrain", "escobar_ndvi.png")

_NDVI_CACHE = None


def _load_ndvi_grid():
    global _NDVI_CACHE
    if _NDVI_CACHE is not None:
        return _NDVI_CACHE
    img = bpy.data.images.load(NDVI_PNG, check_existing=True)
    img.colorspace_settings.name = "Non-Color"
    w, h = img.size
    flat = list(img.pixels)
    grid = [[flat[(y * w + x) * 4] for x in range(w)] for y in range(h)]
    _NDVI_CACHE = (grid, w, h)
    return _NDVI_CACHE


def density_at(nx: float, ny: float) -> float:
    """Bilinear sample of the NDVI density mask at parcel coord (nx, ny).

    nx, ny ∈ [-0.5, +0.5] (clamped); returns float in [0, 1].
    Mirrors the heightmap sampler convention exactly: ny=-0.5 is south
    (bbox.bottom), ny=+0.5 is north (bbox.top). Grayscale 8-bit pixels are
    promoted to float on Blender load, so no extra rescale is needed.
    """
    grid, w, h = _load_ndvi_grid()
    nx_c = max(-0.5, min(0.5, nx))
    ny_c = max(-0.5, min(0.5, ny))
    fx = (nx_c + 0.5) * (w - 1)
    fy = (ny_c + 0.5) * (h - 1)
    x0 = int(fx); x1 = min(x0 + 1, w - 1)
    y0 = int(fy); y1 = min(y0 + 1, h - 1)
    tx = fx - x0; ty = fy - y0
    v00 = grid[y0][x0]; v10 = grid[y0][x1]
    v01 = grid[y1][x0]; v11 = grid[y1][x1]
    v0 = v00 * (1.0 - tx) + v10 * tx
    v1 = v01 * (1.0 - tx) + v11 * tx
    return v0 * (1.0 - ty) + v1 * ty
